---
baseURL: https://blog.bunnieabc.com/
languageCode: en-us
timeZone: Africa/Nairobi
title: BABC Blog
theme: PaperMod
googleAnalytics: UA-235280790-1
params:
  homeInfoParams:
    Title: Yowzha!
    Content: Don't memorize I need you back.
  socialIcons:
  - name: instagram
    url: https://www.instagram.com/bunniestore.ke/
  - name: twitter
    url: https://twitter.com/IhwagiTitus
  - name: github
    url: https://github.com/tito-arch
    
Params:
  ShowReadingTime: true
  linkFullImages: true
  ShowBreadCrumbs: true

 

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
