---
baseURL: https://bunnieabc.com/
languageCode: en-us
timeZone: Africa/Nairobi
title: BABC Blog
theme: PaperMod
defaultTheme: auto
googleAnalytics: UA-235280790-1
params:
  homeInfoParams:
    Title: Yowzha!
    Content: Don't memorize I need you back.

    
Params:
  ShowReadingTime: true
  linkFullImages: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  showShareButtons: true
  ShowPostNavLinks: true
  ShowToc: true
  
  # home-info mode
  homeInfoParams:
    Title: "Yowzha"
    Content: "Don't memorize I need you back"

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/bunniestore.ke/"
    - name: github
      url: "https://github.com/tito-arch"
    - name: linkedin
      url: "https://www.linkedin.com/company/bunnie-abc/"

  editPost:
    URL: "https://github.com/tito-arch/BABC-2/tree/master/content"
    Text: "Edit This Page" # edit text
    appendFilePath: true # to append file path to Edit link
 

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
---