---
baseURL: https://blog.bunnieabc.com/
languageCode: en-us
title: BABC Blog
theme: PaperMod
googleAnalytics: UA-235280790-1
params:
  homeInfoParams:
    Title: Yowzha!
    Content: Don't memorize I need you back.
  socialIcons:
  - name: instagram
    url: https://www.instagram.com/bunniestore.ke/
  - name: twitter
    url: https://twitter.com/IhwagiTitus
  - name: github
    url: https://github.com/tito-arch
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
menu:
  main:
  - url: "/archives/"
    name: Archives
    weight: 3
    identifier: archives
  - url: "/tags/"
    name: Tags
    weight: 2
    identifier: tags
